Update createView call to drop the second param which is meant for $t…
10quality/wpmvc-commands pull request #15
Opened 2020-01-13 19:33 UTC by garretthyder

…emplate

This PR updates the Create Command for creating views so that it uses the template.
The existing call to createView passed $args as a second param, being empty and the createView expecting it to reference the template file instead the view is created empty.
This update drops the $args so createView just uses the default View Template.

2020-01-13 22:00 UTC, amostajo requested changes
Let's make it so `$args[3]` is the name of the template to use.

i.e.
```php
$this->createView($object[1], isset($args[3]) ? $args[3] : 'view.php');
```

This will allow us to call through different view templates in the future, I believe this was the original intent.

2020-01-13 22:22 UTC, garretthyder commented
Hi @amostajo I've updated the PR to use the third arg for the template name and default to view.php if it's not present.
Only question is if we want to update the Add Command as it also triggers the createView call??

2020-01-13 22:34 UTC, amostajo approved these changes

2020-01-13 22:37 UTC, amostajo commented
@garretthyder nice catch!

I guess it would be great to have it in the `AddCommand` as well. Will you add it or do you want me to add it. It should be `$args[4]` in `AddCommand`.

2020-01-13 22:48 UTC, garretthyder commented
Sounds good @amostajo please review the latest commit to this PR as it should now account for a 4th param to introduce the template file.

I guess aside from a merge here the docs will need a tweak.
Cheers

2020-01-13 23:45 UTC, amostajo approved these changes

2020-01-13 23:48 UTC, amostajo commented
@garretthyder Will update the docs.

Let me know if you wish to have an Editor account at the [site](https://www.wordpress-mvc.com/).

2020-01-13 23:48 UTC, merged

2020-01-14 00:46 UTC, garretthyder commented
Thanks @amostajo appreciated.

That would be awesome, happy to contribute to the docs as well as code here while I use your tool for my project. You can find my email on my profile.

2020-01-14 01:03 UTC, amostajo commented
You are welcome! Btw, docs are pages atm, you will find them at the pages section at the dashboard. Will migrate them to a custom type in the future. but, for the time being they are pages.

2020-01-14 01:12 UTC, garretthyder commented
Sounds great, thank you